apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: billing-processor-29962
  namespace: MendPerformance
  annotations:
    github.com/project-slug: MendPerformance/billing-processor-29962
spec:
  type: service
  lifecycle: unknown
  owner: mend.io
